version: '3.8'
services:
  mongodb:
    image: mongo:5.0.7
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    networks:
      - backend
  
  backend-api:
    depends_on:
      - mongodb
    build: ./back
    restart: always
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
    networks:
      - backend
      - frontend
      
  frontend-ui:
    depends_on:
      - backend-api
    build:
      context: ./front
      args:
        - CLIENT_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $VUE_LOCAL_PORT:$VUE_DOCKER_PORT
    networks:
      - frontend  
volumes: 
  db:
networks:
  backend:
  frontend: